language: node_js
sudo: false
node_js:
- '5.10.1'

cache:
  directories:
    - $HOME/.chrome/chromium

before_install:
  - npm install -g gulp typings
  - ./scripts/install_chromium.sh
  - export CHROME_BIN=$HOME/.chrome/chromium/chrome-linux/chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test